// Generate live URLs for a list of rosters so you can load and eyeball them all.
//   node links.mjs                 # from keepers.json
//   node links.mjs picks.json      # from the last sweep
//   node links.mjs --stamp         # write a canonical `link` field into keepers.json
//   node links.mjs --base file:///Users/you/.../knights/   # local instead of deployed
//   node links.mjs --params "palette=0"                    # override the extra query
// Prints the URLs and writes links.html (a clickable list + an "open all" button).
import { readFileSync, writeFileSync } from 'node:fs';
import { BASE, DEFAULT_PARAMS, linkFor } from './score.mjs';

const args = process.argv.slice(2);
let base = BASE;
let params = DEFAULT_PARAMS; // matches the sheet's finished, Vivid look
let stamp = false;
const pos = [];
for (let i = 0; i < args.length; i++) {
  if (args[i] === '--base') base = args[++i];
  else if (args[i] === '--params') params = args[++i];
  else if (args[i] === '--stamp') stamp = true;
  else pos.push(args[i]);
}
const file = pos[0] || 'keepers.json';

const here = (f) => new URL(`./${f}`, import.meta.url).pathname;
const data = JSON.parse(readFileSync(here(file)));
const list = data.keepers || data.picks || data.tiles || data;
if (!Array.isArray(list) || !list.length) { console.error(`no entries in ${file}`); process.exit(1); }

// --stamp: rewrite a canonical `link` (deployed BASE + DEFAULT_PARAMS, ignoring any
// --base/--params override) into each keeper, derived from its url, and save. Keeps
// the committed file's links consistent with `url` — re-run after editing rosters.
if (stamp) {
  if (!data.keepers) { console.error(`--stamp only works on keepers.json (no .keepers array in ${file})`); process.exit(1); }
  data.keepers = data.keepers.map((k) => ({ name: k.name, url: k.url, link: linkFor(k.url), lens: k.lens, ...(k.family ? { family: k.family } : {}), note: k.note }));
  writeFileSync(here(file), JSON.stringify(data, null, 2) + '\n');
  console.log(`stamped link into ${data.keepers.length} keepers -> ${file}`);
}

const rows = list.map((e) => ({ name: e.name || e.url, lens: e.lens || '', url: e.url, href: linkFor(e.url, base, params) }));

for (const r of rows) console.log(`${r.href}`);

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const items = rows.map((r, i) =>
  `  <li><a href="${esc(r.href)}" target="_blank" rel="noopener">${esc(r.name)}</a>` +
  `${r.lens ? ` <span class="lens">${esc(r.lens)}</span>` : ''}` +
  ` <span class="roster">${esc(r.url)}</span></li>`).join('\n');
const html = `<!doctype html><meta charset="utf-8">
<title>knights — ${esc(file)} (${rows.length})</title>
<style>
  body { background:#111; color:#ddd; font:14px/1.6 ui-monospace,Menlo,Consolas,monospace; margin:2rem auto; max-width:780px; padding:0 1rem; }
  h1 { font-size:1rem; font-weight:600; } .muted { color:#888; }
  a { color:#9cf; text-decoration:none; } a:hover { text-decoration:underline; }
  ol { padding-left:2.2rem; } li { margin:.25rem 0; }
  .lens { color:#7c8; font-size:.85em; } .roster { color:#777; font-size:.85em; }
  button { background:#223; color:#9cf; border:1px solid #345; border-radius:5px; padding:.4rem .7rem; font:inherit; cursor:pointer; }
</style>
<h1>knights — ${esc(file)} <span class="muted">(${rows.length} rosters · base <code>${esc(base)}</code>)</span></h1>
<p class="muted">Click a link (⌘-click to open in a background tab), or use the button. Generated by <code>links.mjs</code>; regenerate after editing the source list.</p>
<p><button onclick="document.querySelectorAll('ol a').forEach((a,i)=>setTimeout(()=>window.open(a.href,'_blank','noopener'),i*250))">Open all ${rows.length} in tabs</button> <span class="muted">(your browser may ask to allow pop-ups)</span></p>
<ol>
${items}
</ol>
`;
const outHtml = here('links.html');
writeFileSync(outHtml, html);
console.log(`\n${rows.length} links from ${file} -> ${outHtml}  (open it, click through, or "Open all")`);
